export const data = [
  {
    _id: "60dd376883637991b4952437",
    setup: "My girlfriend, Ruth, fell off the back of my bike.",
    punchline: "I rode on, ruthlessly.",
    type: "ruth",
    likes: [],
    author: { name: "unknown", id: null },
    approved: true,
    date: 1618108661,
    NSFW: false,
  },
  {
    _id: "60dd36aae7c4e649726b049f",
    setup:
      "The Chinese have developed a new pill that increases the average penis size by 3 inches.",
    punchline:
      "Reports say they will use it to interfere with the upcoming U.S. erections.",
    type: "increase",
    likes: [],
    author: { name: "unknown", id: null },
    approved: true,
    date: 1618108661,
    NSFW: true,
  },
  {
    _id: "60dd35f2b9a38fde77d0031f",
    setup: "What’s 30 metres long and has no hair?",
    punchline: "A conga line at a cancer clinic",
    type: "conga",
    likes: [],
    author: { name: "unknown", id: null },
    approved: true,
    date: 1618108661,
    NSFW: false,
  },
  {
    _id: "60dd35a6ebc36138dd391e67",
    setup: "I went to the liquor store today",
    punchline:
      "and I bought a bunch of bottles of wine. I’m getting ready to pay, and the cashier asked “you wanna box for those?” I looked at him and said “nah, I hate violence. Is it cool if I just pay with my card?”",
    type: "bottle",
    likes: [],
    author: { name: "unknown", id: null },
    approved: true,
    date: 1618108661,
    NSFW: false,
  },
  {
    _id: "60dd3602009ef7b4de23ab28",
    setup:
      "I watched a film about a giant crocodile with erectile dysfunction....",
    punchline: "Lake Flaccid.",
    type: "crocodile",
    likes: [],
    author: { name: "unknown", id: null },
    approved: true,
    date: 1618108661,
    NSFW: false,
  },
];
